In [5]:
import numpy as np
import pandas as pd
file_path = 'E:\practicas\Ejercicios\DIVIPOLA_Departamentos.xlsx'
df = pd.read_excel(file_path, skiprows=9)
df

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
C:\Users\HOLL\AppData\Local\Temp\ipykernel_20772\214319621.py:3: SyntaxWarning: invalid escape sequence '\p'
  file_path = 'E:\practicas\Ejercicios\DIVIPOLA_Departamentos.xlsx'

,Código,Nombre,LATITUD,LONGITUD
0,05,ANTIOQUIA,"6,702032125","-75,504557037"
1,08,ATLÁNTICO,"10,677009534","-74,965219492"
2,11,"BOGOTÁ, D.C.","4,316107698","-74,181072702"
3,13,BOLÍVAR,"8,079796863","-74,235148136"
4,15,BOYACÁ,"5,891672889","-72,627880544"
5,17,CALDAS,"5,280139978","-75,274983037"
6,18,CAQUETÁ,"0,798556195","-73,959467561"
7,19,CAUCA,"2,396833887","-76,824232828"
8,20,CESAR,"9,53665993","-73,517831544"
9,23,CÓRDOBA,"8,358549754","-75,792008718"
10,25,CUNDINAMARCA,"4,771120716","-74,431110916"
11,27,CHOCÓ,"5,397581542","-76,942811002"
12,41,HUILA,"2,570143029","-75,584348363"
13,44,LA GUAJIRA,"11,476870077","-72,429510724"
14,47,MAGDALENA,"10,24738355","-74,26175733"
15,50,META,"3,345562732","-72,95645988"
16,52,NARIÑO,"1,571094987","-77,87020496"
17,54,NORTE DE SANTANDER,"8,09513751","-72,881882969"
18,63,QUINDÍO,"4,455241567","-75,689628528"
19,66,RISARALDA,"5,240757239","-76,002444694"
20,68,SANTANDER,"6,693633184","-73,486008938"
21,70,SUCRE,"9,064941448","-75,109817552"
22,73,TOLIMA,"4,03477252","-75,255827095"
23,76,VALLE DEL CAUCA,"3,569858693","-76,62850427"
24,81,ARAUCA,"6,569577215","-70,967323937"
25,85,CASANARE,"5,404064237","-71,601880726"
26,86,PUTUMAYO,"0,3673031","-75,514061833"
27,88,"ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...","12,543115116","-81,717623824"
28,91,AMAZONAS,"-1,54622768","-71,502128578"
29,94,GUAINÍA,"2,727842865","-68,816612721"
30,95,GUAVIARE,"1,924531973","-72,128595691"
31,97,VAUPÉS,"0,64624561","-70,561405657"
32,99,VICHADA,"4,713557125","-69,41400011"
33,NaN,NaN,NaN,NaN
34,Fuente: DANE.,NaN,NaN,NaN
35,Nota: En la actualidad el país se compone de 3...,NaN,NaN,NaN
36,Actualizado al 30 de diciembre de 2024,NaN,NaN,NaN